service: "recv"
frameworkVersion: "3"

custom:
  tableName: ${opt:stage, 'dev'}-recv

provider:
  name: aws
  runtime: nodejs14.x
  logRetentionInDays: 30
  environment:
    TABLE_NAME: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  get:
    handler: index.get
    events:
      - http:
          path: /
          method: get
          request:
            parameters:
              querystrings:
                q: true
  receive:
    handler: index.handler

resources:
  Resources:
    DocumentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: destination
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: destination
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: expiredAt
          Enabled: true
        BillingMode: PAY_PER_REQUEST
